# Copyright (C) 2018-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT

services:
  cvat_server:
    labels:
      - traefik.http.routers.cvat.entrypoints=websecure
      - traefik.http.routers.cvat.tls.certresolver=lets-encrypt

  cvat_ui:
    labels:
      - traefik.http.routers.cvat-ui.entrypoints=websecure
      - traefik.http.routers.cvat-ui.tls.certresolver=lets-encrypt

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.lets-encrypt.acme.tlschallenge=true
      - --certificatesresolvers.lets-encrypt.acme.email=${ACME_EMAIL:?err}
      - --certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cvat_letsencrypt:/letsencrypt

  filegator:
    image: filegator/filegator
    labels:
      - traefik.http.routers.filegator.rule=Host(`upload-pidrone.kavabanga.team`)
      - traefik.http.routers.filegator.entrypoints=websecure
      - traefik.http.routers.filegator.tls.certresolver=lets-encrypt
    volumes:
      - filegator_data:/var/www/html/repository
    environment:
      FILEGATOR_CONFIGURATION: '/var/www/html/config.php'

volumes:
  cvat_letsencrypt:
  filegator_data:
